name: Release Trigger

on:
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'
        required: true
        default: '1'
      releaseVersion:
        description: 'Release version'
        required: true
        default: 'x.xx.x'
      nextVersion:
        description: 'Next version'
        required: true
        default: 'x.xx.x-SNAPSHOT'

env:
  MAVEN_ARGS: "--no-transfer-progress --errors --fail-at-end --show-version"

jobs:
  trigger-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build
        run: ./mvnw verify
      - name: Create Release Notes
        uses: spring-io/github-changelog-generator@v0.0.12
        with:
          milestone: ${{ github.event.inputs.milestoneId }}
          changelog-file: ${{format('{0}{1}{2}', '.chglog/', github.event.inputs.releaseVersion, '.md')}}
          config-file: '.github/release-notes.yml'
          token: ${{ secrets.GITHUB_TOKEN }}

